<a href="https://colab.research.google.com/github/Dhrubaraj-Roy/Python-for-Machine-Learning/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
n2 = np.zeros((10,10))

In [ ]:
n2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
n3 = np.full((3,3), 55)

In [ ]:
n3

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [ ]:
n4=np.arange(10,200,5)
n4

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])

In [4]:
#vertically stack those two array
n5 = np.array([1,2,3])
n6 = np.array([4,5,6])

In [5]:
np.vstack((n5,n6))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((n5,n6))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.column_stack((n5,n6))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1.shape

(2, 4)

In [ ]:
n1.shape = (4,2)

In [ ]:
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.random.randint(100,1000,100)

array([296, 328, 207, 748, 902, 805, 538, 294, 607, 188, 687, 687, 166,
       277, 845, 306, 119, 806, 736, 858, 486, 558, 847, 261, 636, 256,
       158, 223, 881, 681, 786, 228, 598, 275, 585, 318, 217, 245, 329,
       383, 790, 239, 153, 503, 679, 260, 894, 239, 557, 237, 476, 218,
       744, 783, 595, 191, 395, 911, 773, 793, 498, 996, 201, 751, 279,
       944, 954, 465, 529, 878, 457, 508, 926, 568, 195, 318, 663, 681,
       857, 167, 136, 836, 210, 653, 546, 626, 297, 861, 762, 149, 304,
       811, 987, 276, 903, 910, 823, 469, 661, 231])

In [ ]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([40,50,60,70,80])
np.intersect1d(arr1,arr2)

array([40, 50])

In [ ]:
np.setdiff1d(arr1,arr2)

array([10, 20, 30])

In [ ]:
np.setdiff1d(arr2,arr1)

array([60, 70, 80])

In [ ]:
arr3 = np.array([10,20])
arr4 = np.array([30,40])
np.sum([arr3,arr4])

100

In [ ]:
np.sum([arr3,arr4], axis=0)

array([40, 60])

In [ ]:
np.sum([arr3,arr4], axis=1)

array([30, 70])

In [ ]:
n1  = np.array([10,20,30])
n1 = n1 + 5
n1

array([15, 25, 35])

In [ ]:
n1 = n1 - 5
n1

array([10, 20, 30])

In [ ]:
n1 = n1 * 5
n1

array([ 50, 100, 150])

In [ ]:
n1 = n1 / 5
n1

array([10., 20., 30.])

In [ ]:
n1 = np.random.randint(1,100,10)

In [ ]:
n1

array([56, 90, 32, 85, 40, 39, 89, 76, 33, 22])

In [ ]:
np.mean(n1)

56.2

In [ ]:
np.median(n1)

48.0

In [ ]:
np.std(n1)

25.083062014036482

In [ ]:
n1

array([56, 90, 32, 85, 40, 39, 89, 76, 33, 22])

In [ ]:
np.save('myarray', n1)

In [ ]:
new = np.load('myarray.npy')

In [ ]:
new

array([56, 90, 32, 85, 40, 39, 89, 76, 33, 22])