<a href="https://colab.research.google.com/github/Dhrubaraj-Roy/Python-for-Machine-Learning/blob/main/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
type(n1)

numpy.ndarray

In [34]:
n2 = np.zeros((10,10))

In [35]:
n2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
n3 = np.full((3,3), 55)

In [37]:
n3

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [38]:
n4=np.arange(10,200,5)
n4

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
       140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195])

In [39]:
#vertically stack those two array
n5 = np.array([1,2,3])
n6 = np.array([4,5,6])

In [40]:
np.vstack((n5,n6))

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.hstack((n5,n6))

array([1, 2, 3, 4, 5, 6])

In [42]:
np.column_stack((n5,n6))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1.shape

(2, 4)

In [44]:
n1.shape = (4,2)

In [45]:
n1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [46]:
np.random.randint(100,1000,100)

array([355, 672, 918, 125, 545, 720, 649, 290, 945, 958, 540, 549, 970,
       459, 767, 675, 757, 466, 780, 924, 914, 456, 487, 188, 986, 265,
       295, 954, 286, 694, 360, 789, 255, 715, 213, 283, 714, 166, 518,
       175, 609, 706, 397, 731, 928, 761, 255, 670, 196, 536, 101, 945,
       487, 614, 105, 496, 199, 786, 774, 591, 352, 202, 526, 575, 318,
       671, 717, 696, 561, 741, 128, 120, 143, 316, 660, 647, 602, 479,
       698, 270, 390, 614, 916, 661, 591, 137, 430, 204, 469, 396, 874,
       937, 334, 747, 247, 870, 265, 469, 184, 215])

In [47]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([40,50,60,70,80])
np.intersect1d(arr1,arr2)

array([40, 50])

In [48]:
np.setdiff1d(arr1,arr2)

array([10, 20, 30])

In [49]:
np.setdiff1d(arr2,arr1)

array([60, 70, 80])

In [50]:
arr3 = np.array([10,20])
arr4 = np.array([30,40])
np.sum([arr3,arr4])

100

In [51]:
np.sum([arr3,arr4], axis=0)

array([40, 60])

In [52]:
np.sum([arr3,arr4], axis=1)

array([30, 70])

In [53]:
n1  = np.array([10,20,30])
n1 = n1 + 5
n1

array([15, 25, 35])

In [54]:
n1 = n1 - 5
n1

array([10, 20, 30])

In [55]:
n1 = n1 * 5
n1

array([ 50, 100, 150])

In [56]:
n1 = n1 / 5
n1

array([10., 20., 30.])

In [57]:
n1 = np.random.randint(1,100,10)

In [58]:
n1
n1.sort()
n1

array([ 9, 10, 31, 37, 51, 69, 78, 80, 89, 96])

In [59]:
np.mean(n1)

55.0

In [60]:
np.median(n1)

60.0

In [61]:
np.std(n1)

30.403947112176077

In [31]:
n1

array([ 2,  9, 22, 25, 39, 64, 68, 90, 92, 97])

In [62]:
np.save('myarray', n1)

In [63]:
new = np.load('myarray.npy')

In [64]:
new

array([ 9, 10, 31, 37, 51, 69, 78, 80, 89, 96])